#[toolchain]
#channel = "nightly"
#components = ["rust-src"]
## targets = ["riscv32imc-unknown-none-elf"]

#[toolchain]
#channel = "esp"
#components = ["rustfmt", "rustc-dev"]
#targets = ["xtensa-esp32-none-elf"]

[toolchain]
channel    = "nightly-2023-11-14"
components = ["rust-src"]
